apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
      - name: posts-service
        image: lalitdk018/linkup-app-posts-service:latest


        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
 
        env:
          # Activate the k8s profile
          - name: SPRING_PROFILES_ACTIVE
            value: k8s

          # Spring Boot database connection (matches application.properties)
          - name: DB_USER
            value: user
          - name: DB_PASSWORD
            value: password
          - name: DB_NAME
            value: postDB
          - name: DB_SERVICE
            value: post-db
        ports:
        - containerPort: 9020


---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  selector:
    app: posts-service
  ports:
    - port: 80
      targetPort: 9020



